name: "Southern Flame Bahá'í  Summer School"
favicon: null
layout_spectrum: 0.46776971966028214
typography_spectrum: 0.51002
title: "Southern Flame Bahá'í  Summer School"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e8435'
    - '#adad7a'
    - '#658b70'
    - '#14421e'
  brandStrength: 0.08452202915214002
  lightness: 0.5755148073658347
  saturation: 0.1439882901031524
  rhythmicContrast: 0.14233524748124182
purpose: []
